### ISSUE TITLE
Navigation from Landing to Login Page

### ISSUE THREAD

**Issue by ibishop** [evscott/Rambl#201]
"TypeError: Cannot read property 'hasCurrEvent' of null" when clicking login page from landing

**Comment by morgankbender** [comment]
Current problem on login (not authenticated prior):
![image](https://user-images.githubusercontent.com/35503542/55270158-7c83a200-527a-11e9-8553-475895131944.png)

Commenting out lines 2 and 15 in getTripTimes:
![image](https://user-images.githubusercontent.com/35503542/55270229-4c88ce80-527b-11e9-90b8-7c6d78a40b59.png)
![image](https://user-images.githubusercontent.com/35503542/55270232-5579a000-527b-11e9-944b-fafe3bf06ef1.png)
(problem is solved, but events are not sorted properly)

@gzinck and @evscott want to take a look at this?

**Comment by gzinck** [comment]
This should now be fixed with PR #202 !
